### ISSUE TITLE
i think i found this twilight sparkle person who made the original

### ISSUE THREAD

**Issue by EnderNon** [ArjixWasTaken/3y3#1]
https://gist.github.com/twilight-sparkle-irl

https://spacehey.com/twilight

https://synthetic.garden/

their twitter is linked as yourcompanionai though the account is deleted

I also found a few tweets that seem to be replying to yourcompanionai but the account is deleted so I can't find what it said [first](https://x.com/eevee/status/1198638662633705474) [second](https://x.com/DominicTarason/status/1538612104315510785)

**Comment by ArjixWasTaken** [comment]
yep, that looks like the correct person!

**Comment by ArjixWasTaken** [comment]
thx!
